# Generated by Django 4.1.7 on 2023-03-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Demandeur',
        ),
        migrations.RenameField(
            model_name='demandeur',
            old_name='category',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='demandeur',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='demandeur',
            old_name='price',
            new_name='prenom',
        ),
    ]
