# Generated by Django 4.1.7 on 2023-03-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_produit_demandeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeur',
            name='tel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
