# Generated by Django 4.1.7 on 2023-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_demandeur_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeur',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
